services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: lucassb
      POSTGRES_PASSWORD: lucassb
      POSTGRES_DB: pixelbreeders
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    # ensures DB is ready before backend tries to connect
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lucassb -d pixelbreeders"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      
    environment:
      - DATABASE_URL=postgresql://lucassb:lucassb@db:5432/pixelbreeders
      - TMDB_API_KEY=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1NmI5MmY0N2QwOGNmZTEzYjMxOThkNjFlODU3NjkzNiIsIm5iZiI6MTc3MDkxNjU3MS45NDMsInN1YiI6IjY5OGUwYWRiNDcwZWZjMzRiNDQxNmVhNiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.DmXH3cBPl-M54tJzTNatIios8tA8iK65R1q-SLrdjkY
      - TMDB_BASE_URL=https://api.themoviedb.org/3
      - PYTHONPATH=/app
      - JWT_SECRET_KEY=pixelbreeders
      - CACHE_REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
    # handles migrations when first deploy or not
    command: >
      sh -c "
      echo 'Checking for migrations...';
      if [ ! -d 'migrations' ]; then
        echo 'No migrations folder found. Initializing DB...';
        flask db init;
        flask db migrate -m 'Initial Auto-Migration';
        flask db upgrade;
      else
        echo 'Migrations folder found. Applying any pending updates...';
        flask db upgrade;
      fi;
      echo 'Starting Application...';
      exec python app.py;
      "

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

volumes:
  postgres_data: