services:
  - type: web
    name: pixelbreeders-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask db upgrade && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        sync: false # to enter manually
      - key: REDIS_URL
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false

  - type: static
    name: pixelbreeders-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: build
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: pixelbreeders-backend
          property: url